### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by ismay** [AtomLinter/linter-eslint#119]
```bash
TypeError: Cannot read property 'split' of undefined
  at findFile (/Users/me/.atom/packages/linter/lib/util.coffee:16:19)
  at Object.provider.lint (/Users/me/.atom/packages/linter-eslint/lib/linter-eslint.coffee:57:20)
  at /Users/me/.atom/packages/linter/lib/editor-linter.coffee:79:24
  at /Users/me/.atom/packages/linter/lib/editor-linter.coffee:78:25
  at Set.forEach (native)
  at EditorLinter._lint (/Users/me/.atom/packages/linter/lib/editor-linter.coffee:72:26)
  at EditorLinter.lint (/Users/me/.atom/packages/linter/lib/editor-linter.coffee:66:18)
  at /Users/me/.atom/packages/linter/lib/editor-linter.coffee:22:37
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1183:25
```

This error is being thrown whenever I open a `.js` file with atom. I've installed `linter` and `linter-eslint`. And the error came up after my installation of linter eslint (had no problems with jshint for example).

I've installed eslint and babel-eslint locally, and other than that I've absolutely no idea what's going wrong..

**Comment by ismay** [comment]
When I turn off `Disable when no eslintrc file in path`, the error that pops up whenever I open a javascript file changes to:

```
ReferenceError: relative is not defined
  at Object.provider.lint (/Users/me/.atom/packages/linter-eslint/lib/linter-eslint.coffee:75:47)
  at /Users/me/.atom/packages/linter/lib/editor-linter.coffee:79:24
  at /Users/me/.atom/packages/linter/lib/editor-linter.coffee:78:25
  at Set.forEach (native)
  at EditorLinter._lint (/Users/me/.atom/packages/linter/lib/editor-linter.coffee:72:26)
  at EditorLinter.lint (/Users/me/.atom/packages/linter/lib/editor-linter.coffee:66:18)
  at /Users/me/.atom/packages/linter/lib/editor-linter.coffee:22:37
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1183:25
```

**Comment by AsaAyers** [comment]
it looks like `@cwd` is undefined [here](https://github.com/AtomLinter/linter-eslint/blob/master/lib/linter-eslint.coffee#L57). I suspect this is related to the 1.0.0 release of `linter` yesterday, but I don't know how to reproduce this error. For me it isn't as simple as opening a `.js` file.

**Comment by ismay** [comment]
I suspect it's related to https://github.com/AtomLinter/linter-eslint/blob/master/lib/linter-eslint.coffee#L75. I have an `.eslintignore` file, and when I remove it, the errors disappear and everything works as expected.

**Comment by iam4x** [comment]
It's my bad, haven't tested `.eslintignore` feature. Let me fix this :+1:

**Comment by ismay** [comment]
@iam4x Ah ok, cool!

**Comment by iam4x** [comment]
I've released a new version, is the fix working for you @ismay ?

**Comment by ismay** [comment]
@iam4x Yep, working as expected. Succesfully ignores files and doesn't throw the `relative is undefined` error. Thanks for the quick reply!

**Comment by iam4x** [comment]
No problem!

**Comment by bjmiller** [comment]
This is still a problem for me, whether I have "Disable when no eslintrc file in path" or not.

**Comment by iam4x** [comment]
@bjmiller Updating to `1.0.1` and reloading the editor doesn't fix it for you?

**Comment by bjmiller** [comment]
Correct.  
```
├── linter@1.0.2
├── linter-eslint@1.0.1
```

**Comment by bjmiller** [comment]
Here's the full error, FWIW.
```
TypeError: Cannot read property 'split' of undefined
    at findFile (/Users/brian/.atom/packages/linter/lib/util.coffee:19:21)
    at Object.provider.lint (/Users/brian/.atom/packages/linter-eslint/lib/linter-eslint.coffee:66:26)
    at /Users/brian/.atom/packages/linter/lib/editor-linter.coffee:120:35
    at /Users/brian/.atom/packages/linter/lib/editor-linter.coffee:119:32
    at Set.forEach (native)
    at EditorLinter._lint (/Users/brian/.atom/packages/linter/lib/editor-linter.coffee:107:32)
    at EditorLinter.lint (/Users/brian/.atom/packages/linter/lib/editor-linter.coffee:97:31)
    at /Users/brian/.atom/packages/linter/lib/editor-linter.coffee:34:26
    at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1183:25
```

**Comment by iam4x** [comment]
@bjmiller Are you using `Eslint Rules Dir` ?

**Comment by bjmiller** [comment]
Yes.  I have it set to ~/.atom, where I have an esilnt.json file.

**Comment by iam4x** [comment]
@bjmiller Released an update, doest it fixes for you?

**Comment by bjmiller** [comment]
I'll check.  I had to roll back so I could keep working...

**Comment by bjmiller** [comment]
Nope.  I'm still getting the same error with 1.0.2 .  :disappointed:

**Comment by iam4x** [comment]
@bjmiller Okey I'll take more time to investigate later tonight g2g

**Comment by bjmiller** [comment]
Thank you for looking into it.

**Comment by iam4x** [comment]
It should be fixed with v1.0.3 now :+1:

**Comment by bjmiller** [comment]
Looks good.  Thanks for the help!
