### ISSUE TITLE
Something change with 2.0.0 Configuration?

### ISSUE THREAD

**Issue by framerate** [AtomLinter/linter-eslint#144]
I upgraded and now get this error. Worked fine this morning. Point me in a good direction?
<img width="472" alt="screen shot 2015-07-09 at 4 09 01 pm" src="https://cloud.githubusercontent.com/assets/74291/8608951/dd749264-2654-11e5-822e-04e30bf7ef9a.png">

**Comment by iam4x** [comment]
Yes the package is now using the ESLint CLI tool instead of node module.

Can I have more information about your setup? Local ESLint (`$ npm i --save-dev eslint`) or global one (`$ npm -g eslint`)? There's a new option for `ESLint path` you can set with result of `$ which eslint`.

**Comment by framerate** [comment]
I typically use the local one.

```
    "eslint": "^0.22.1",
```

currently in this project

**Comment by iam4x** [comment]
From where do you start Atom?

**Comment by framerate** [comment]
At this point, I just open it from my dock or `atom ./` from the command line.

```
which atom
/usr/local/bin/atom
```

**Comment by iam4x** [comment]
Could you give me the result of `atom.project.getPaths()[0]` in the atom console?

**Comment by framerate** [comment]
```"/Users/framerate/code/karma/dashboard"```

**Comment by framerate** [comment]
"/Users/framerate/code/karma/dashboard"

**Comment by iam4x** [comment]
I've released a new version, could you quit Atom and ` $apm uninstall linter-eslint && apm install linter-eslint` ?

**Comment by framerate** [comment]
Done and it's all fixed for me! Nice work!

**Comment by iam4x** [comment]
Cool thank's!

**Comment by tundrax** [comment]
The problem still exists with multi-folder projects where ```atom.project.getPaths()[0]``` is the first folder, which may be irrelevant to the file being edited.

**Comment by framerate** [comment]
Yeah I closed my windows and reopened and am still getting errors. This is odd... (reopened)

**Comment by ide** [comment]
I put up a PR that might fix this: https://github.com/AtomLinter/linter-eslint/pull/145. You could try using my fork to see if it helps you:

```
git clone git@github.com:ide/linter-eslint.git
cd linter-eslint
git checkout search-up
apm link
```

**Comment by tundrax** [comment]
@ide the problem is with line:90 which reassigns ```cwd``` to the first folder in the project.

**Comment by miljan-aleksic** [comment]
I get this one:

```
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Object.<anonymous> (/Users/user/.atom/packages/linter-eslint/lib/linter-eslint.js:120:28)
    at GeneratorFunctionPrototype.next (native)
    at step (/Users/user/.atom/packages/linter-eslint/lib/linter-eslint.js:7:273)
```

**Comment by aaronjensen** [comment]
@miljan-aleksic i got that too and followed the instructions of quitting, uninstalling, reinstalling via apm and it worked.

**Comment by miljan-aleksic** [comment]
I already tried that without results :(

**Comment by aaronjensen** [comment]
annnd it just came back for me. I'm probably going to revert to 1.x, this one doesn't really work.

**Comment by MrBoolean** [comment]
Again :/ unfortunately, this is the 3 time in a row an update breaks the plugins. is it possible to avoid such updates?

**Comment by iam4x** [comment]
@MrBoolean This update is vital for the package, we have new codebase which is running the CLI tool instead of programatically ESLint. It was source of weird errors, like no support of `reset` in `.eslintrc` of custom rules.

I'll try to do my best to fix the issues for the users.

Thank's @ide for the PR :+1:

**Comment by iam4x** [comment]
Pushed a new version is it solving the issues? If not:

* Is ESLint installed localy or globaly?
* How do you open Atom editor?
* What is the absolute path of Atom when you open it (example with cli `$ atom /path/to/project`)?
* What is the absolute path of the file you are editing while getting this issue?

**Comment by sebastiendavid** [comment]
Hi, after update I have this error in linter-eslint.js line 125:

```[Linter-ESLint] error while parsing ouput```

```javascript
const output = await exec(eslint, params, {stdin: TextEditor.getText(), cwd})

// Parse the ouput, take the needed stuff
let results
let messages
try {
      results = JSON.parse(output).results
```

The __output__ is an empty string.
__eslint__ = ```/usr/local/bin/eslint```
__params__ = ```["--stdin-filename", "src/utils/Worker.js", "--config", "src/.eslintrc", "--format", "/Users/sdavid/.atom/packages/linter-eslint/node_modules/eslint-json/json.js", "--stdin"]```
__cwd__ is my project root folder

So eslint is installed globaly, I open Atom from the OSX app bar, the path of Atom is ```/usr/local/bin/atom```.

Hope it helps.

**Comment by sebastiendavid** [comment]
Another information: when I remove the eslint global path in your plugin global conf, it does not find the local eslint although eslint is installed locally in the project.

**Comment by iam4x** [comment]
@sebastiendavid This is an issue with Atom launcher I think. Let's continue discussion into #149
