### ISSUE TITLE
Please do not require the `linter` package

### ISSUE THREAD

**Issue by nmote** [AtomLinter/linter-eslint#212]
Nuclide has released a [suite of packages](https://github.com/facebook/nuclide/tree/master/pkg/nuclide/diagnostics) that displays diagnostic results.

However, Nuclide users still [cannot use this package](https://github.com/facebook/nuclide/issues/190) because it [will not start](https://github.com/AtomLinter/linter-eslint/blob/master/lib/linter-eslint.coffee#L11) unless the `linter` package is installed.

Please remove that requirement, or at least relax it to allow the `nuclide-diagnostics` suite of packages to stand in for the `linter`.

**Comment by admmasters** [comment]
Yeah this is key to my workflow - having to lint through the terminal at the moment :-p

**Comment by Arcanemagus** [comment]
This should be fixed by fixing this issue: https://github.com/AtomLinter/linter-eslint/issues/207

Although that would install `linter` if you don't have it installed already, the check causing this problem could then be removed as it can be assumed that the package is at least installed, so checking that it is enabled becomes redundant. You would then be able to just disable `linter` and use `nuclide-diagnostics`.

**Comment by nmote** [comment]
Actually, by default the `atom-package-deps` package will not allow the user to disable the package. If the user tries, it will enable it again next time your package calls `install()`. If you do end up using that package, it would be great if you called it with `enablePackages = false`: https://github.com/steelbrain/package-deps/blob/master/lib/main.js#L9

Anyway, why not just let users install a package of their choice, instead of forcibly installing one for them?

**Comment by Arcanemagus** [comment]
The problem that is meant to solve is that far too many users are installing the linter providers without a consumer, and then wondering why it doesn't do anything. The idea was to make sure there was a consumer for the provider installed. You make an excellent point though about `install()` forcing the package to be enabled, I'll have to go back and submit a PR to the two I've updated to make it so they don't force `linter` to be enabled all the time.

With that setup, if `linter` isn't installed it will be installed and enabled, but if it is already installed (regardless of enable state) nothing will happen. Meaning you can just leave `linte` installed but disabled and use `nuclide-diagnostics`.

**Comment by nmote** [comment]
Awesome, I would appreciate that work. Perhaps it would be reasonable to check to see if the `nuclide-diagnostics` packages are enabled, and if so don't even install the `linter`. That way, users with nothing to consume diagnostics will still get something installed, but Nuclide users won't to jump through the hoop of disabling the `linter` package.

**Comment by steelbrain** [comment]
@nmote here's a side note, `package-deps` only activates packages if they are not previously installed. So if a person installs `linter`, then deactivates it. It'll not be enabled.

**Comment by nmote** [comment]
@steelbrain That is not the case. I just installed `linter-ruby` to check, and it re-enabled the `linter` package. I disabled it again, then restarted Atom, and it re-enabled the `linter` package again.

**Comment by steelbrain** [comment]
@nmote, Yep, I realized after writing that but had no time to edit. We can push an update with `enablePackages` set to false. But here's the question I have in mind: Why invent diagnostics when there's a linter already present? I have talked with James and he says it was because it was a bottleneck back then, but now that we have implemented diffed updates. I would advise you guys revert back, he said he would convey my messages to the nuclide team, but I guess he's been busy.

**Comment by bolinfest** [comment]
@steelbrain I thought I put all of this this in a public commit message or `README.md`, but if I did, I can't find it now. Basically, our decision to introduce the `nuclide-diagnostics-*` suite of packages came down to:

* We wanted to have a "push" model instead of a "pull" model for updating diagnostics, as explained in https://github.com/facebook/nuclide/tree/master/pkg/nuclide/diagnostics/store#readme.
* The list view for the `linter` did not scale for us. If you had 10,000 diagnostics (which happens for some of our users), then there was a DOM with 10,000 rows, which was very expensive to redraw. This would lock up Atom for our users. By comparison, the `nuclide-diagnostics-ui` uses the [FixedDataTable](https://facebook.github.io/fixed-data-table/) for React, which only renders the rows that are currently in view. This is a non-trivial UI component to implement because you have to re-implement scrolling to make it work properly.
* Our internal users were frustrated by the callout bubble from the `linter` package. It frequently obscured their view of their own code.
* Our internal users found the `linter`'s language around Project vs. File diagnostics confusing.

The differences between what we wanted and what the `linter` did seemed great enough that we decided to go with our own implementation.

From talking to the Atom core team, it seems that they would like to create an ecosystem where developers should feel free to build packages with overlapping behavior and then let the community decide. In his CodeConf talk, @benogle cited how the third-party `autocomplete-plus` package grew to become the community standard, replacing the Atom team's own `autocomplete` package, and then `autocomplete-plus` became part of core.

I think it's still a bit early in Atom's history to say what the "best" way to create a linter/diagnostics package is. I'm not saying that Nuclide's is the best and should be bundled into core tomorrow, but it's working better for us, so we're going to continue to develop and use it.

**Comment by steelbrain** [comment]
@bolinfest I am glad someone finally answered. About point 1, we have a lot of IDE packages for atom that consume linter and use the push API instead of the pull one. For that linter provides a self-api where you can set API and it'll work in a push manner. The message registry will in no time notice the change and dispatch a diff to it's observers to update themselves. I can even provide you a couple of PRs where they implemented it to give you an idea of how it looks like. (I am talking about atom-typescript, atom-omnisharp, dart lang tools and more...)
About point 2, We have been working on that, and if you were able to do it in diagnostics, You could've done that in linter too and I would've loved to accept that and it would've benefitted a wider range of people. I like the idea of rendering only what's in view, however 10k error messages are a rare case, I have tested linter with a few k messages and it works, it does lag a bit but that's because of the atom decoration buffers.
About point 3, we have a configuration to disable that inline bubble, I guess no one bothered to browse settings view :)
About finding Project and File confusing, We could've renamed it to something that wasn't confusing if you had proposed us. It would've been less effort and more rewarding.

I never said that the linter is best, what I have always been saying is that collaboration is what OSS is all about. If you don't like a feature, send a PR and improve it. If you don't like something at all discuss with us and we'll add an option to disable it or maybe even remove it if it's bugging a lot of people. That in my opinion is the most efficient approach and is the way forward :)
What do you think?

**Comment by steelbrain** [comment]
I have been trying to convey my message to the Nuclide Team through James and I even sent you a direct email this morning. I have said it quite a few times that we at linter are always open to ideas and have always solved requests/bugs from facebook with high priority. It would be a lot efficient if both the teams were working on one implementation. I agree that you would want a simpler API for the push behavior, We can discuss how we can further simplify it. But please reach us at least once before assuming something :)

**Comment by bolinfest** [comment]
Any update on this specific issue?

**Comment by steelbrain** [comment]
We have fixed this in the helper module, it will no longer activate by default.

**Comment by nmote** [comment]
But this package doesn't actually use `atom-package-deps`. Instead it throws an error and refuses to load if the `linter` package is not present: https://github.com/AtomLinter/linter-eslint/blob/master/lib/linter-eslint.coffee#L10

**Comment by steelbrain** [comment]
Oh well :sweat_smile:
