### ISSUE TITLE
[Atom bug!] Eslint worker continually crashes/dies

### ISSUE THREAD

**Issue by viveleroi** [AtomLinter/linter-eslint#348]
It's only begun recently, but the worker seems to die very frequently. A message displays that the worker died, a new one will be started, and to check the console.

The only message in the console is:

    ESLint Worker Info 
    "(10126,0x7fff7c9c8300) malloc: *** error for object 0x7f929343b660: pointer being freed was not allocated *** set a breakpoint in malloc_error_break to debug "

linter 1.11.3
linter-eslint 5.2.4
eslint v1.5.1

**Comment by IanVS** [comment]
This has been reported many times, most recently in https://github.com/AtomLinter/linter-eslint/issues/347.  

The upshot is that it is an Atom bug which is fixed in the beta version.

**Comment by dlmanning** [comment]
Perhaps it would be a good idea to leave the issue open so people stop reporting it?

**Comment by Arcanemagus** [comment]
Worth a shot :wink:.

**Comment by dlmanning** [comment]
;) :+1:

**Comment by viveleroi** [comment]
It would have worked for me, I looked through all open issues. I didn't check closed issues because it seemed clear it wasn't resolved.

**Comment by iam4x** [comment]
@Arcanemagus You shoud link to the Atom issue, this will inform users about it.

**Comment by nmn** [comment]
linter-eslint has been failing for many days for me now.

**Comment by IanVS** [comment]
@nmn Are you using the beta version of Atom?

**Comment by SpainTrain** [comment]
convenience link https://github.com/atom/atom/releases/tag/v1.3.0-beta6

**Comment by Moeriki** [comment]
That's awesome. Updating to beta at once. Thanks for the link @SpainTrain

**Comment by Arcanemagus** [comment]
Atom v1.3.0 is released, anyone who hasn't moved on to the beta channel should update to get the fix for this.
