### ISSUE TITLE
Configuration option to disable notifications

### ISSUE THREAD

**Issue by suchipi** [AtomLinter/linter-eslint#735]
Over the last few weeks, I have been getting a lot of error notifications from stuff like https://github.com/AtomLinter/linter-eslint/issues/700. The solution in #700 (to upgrade to eslint@3.5.0) is not an option for me; I am using a legacy eslint@2.x config that would take a lot of time to upgrade to 3.5.0 because it uses many plugins. Running eslint on its own does not cause issues, and I don't want to spend a ton of time and change many lines of code due to rule incompatibilities and changes just so my editor stops annoying me.

99.9% of the time that an error has popped up from linter-eslint while I was typing, I didn't care and could safely dismiss it. It is very irritating that these ignorable errors are popping up while I type.

Since I am aware that certain rule checks fail due to race conditions on save, and I want to ignore them, it'd be nice to have an option in linter-eslint to disable all notifications from that package, or at least all error notifications.

**Comment by Arcanemagus** [comment]
@suchipi There should be no race condition issues in the currently released version. Any errors you are seeing should solely be due to buggy rules.

As for being unable to update, I'm not entirely sure what the best course of action is. We _could_ add a configuration option that disables showing these errors to you and makes `linter-eslint` do what it can to correct the positions on its own, but I don't want people to enable that and then just leave it enabled forever as they will never know when things aren't behaving as they should.

@AtomLinter/linter-eslint What do you think about implementing the option described above, defaulting to disabled, _and_ having it set itself to disabled on package activation? Users will need to enable it whenever they restart Atom that way.

**Comment by suchipi** [comment]
What if the package had a setting that was a blacklist of linter rules to not show errors for? An additional optimization would be to add a "Never show errors for this rule" button to the error notification (that adds that rule name to the blacklist).

**Comment by Arcanemagus** [comment]
As discussed in https://github.com/AtomLinter/linter-eslint/issues/732#issuecomment-252773618, we aren't interested in maintaining a database of what rules are broken in what way for which versions of ESLint.

Although that does bring up an alternative implementation: A per-session list of rules to ignore

That sounds more intrusive and annoying than the auto-disabling option though. Maybe a button on there that just enables that option for the user?

**Comment by suchipi** [comment]
The list of what rules are broken wouldn't be maintained by you; I'm proposing a user-editable text field in the package's settings, which would be blank by default, but could be filled with space- or comma-delimited rule names that errors should not be shown for.

>That sounds more intrusive and annoying than the auto-disabling option though. Maybe a button on there that just enables that option for the user?

Not sure what auto-disabling feature or option you're referring to, here...

I'd prefer changes that are set in a user setting to changes that are set per-session. I don't want to have to do the same thing every time I open Atom each morning. As far as I'm concerned, having to make a change every session is not any better than the errors popping up while I type; both are bad UX that makes me feel like I'm fighting my editor.

**Comment by camsong** [comment]
The notification disappear after I upgraded to `8.0.0`

**Comment by Arcanemagus** [comment]
Came up with a solution that I actually like, which is better than all the ones I've came up with before or seen in the myriad of issues where this has been discussed 😛.

My current plan is to generate a "message" for the first line of the file that states something along the lines of "Invalid points from ESLint encountered, please see the console for details and report this problem."

In the console would be the details of the original points, what they were corrected to, and the rule + message that were associated with them.

With this solution the notification that something was wrong with the output of ESLint would be no more intrusive than the other messages from the linter, and would automatically go away if the error causing it was solved.

**Comment by suchipi** [comment]
So it would be an inline linter error on line 1, instead of an error notification? That sounds good.

**Comment by Tectract** [comment]
Feature to "disable all notifications" still missing? I recommend this issue be re-opened until the requested feature is implemented.

**Comment by Arcanemagus** [comment]
@Tectract can you please file a **new** issue describing what "notifications" you are seeing? The only notifications that are currently shown are errors preventing ESLint from running.
